# Generated by Django 4.1.7 on 2023-03-03 19:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.CharField(max_length=500)),
                ('created', models.DateField(default=django.utils.timezone.now)),
                ('status', models.CharField(blank=True, choices=[('done', 'done'), ('undone', 'undone')], max_length=100, null=True)),
                ('updated', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
